[tools]
"tuist" = "4.117.0"
"swiftlint" = "0.54.0"
"swiftformat" = "0.52.10"
"git-cliff" = "2.6.0"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
swift = "https://github.com/fcrespo82/asdf-swift"
podman = "https://github.com/tvon/asdf-podman.git"
